blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/drawiks/fastapi-sliding-window/discussions
    about: Please ask and answer usage questions here.
